server:  
  port: ${PORT:9999}

spring:  
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/default?ssl=false
    username: postgres
    password: qwellk123
    driver-class-name: org.postgresql.Driver
    schema: classpath:/script/schema.sql
    data: classpath:/script/data.sql
    
logging:
  level:
    org.springframework.security: DEBUG