server:  
  port: ${PORT:9999}
  servlet:
    session:
      cookie:
        name: AUTHSESSION

spring:  
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/default?ssl=false
    username: postgres
    password: qwellk123
    driver-class-name: org.postgresql.Driver
    schema: classpath:/script/schema.sql
    data: classpath:/script/data.sql
  cloud:
    refresh:
      refreshable: none
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

logging:
  level:
    org.springframework.security: DEBUG

google:
  client:
    clientId: 1013554836557-jhe5j1nb7i4qb2sljf4og06p6e2bsrfj.apps.googleusercontent.com
    clientSecret: Anw29u5BKUmSNHyuHhNlT19z
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope:
    - openid
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: true